"""Review a selected subset of the supplied DB3K 442 identity index.

IDs are scoped by database/build/section. Labels aren't technical certification.
Nothing reads binary structures as guessed ranges, bands, prices or Pk.
"""
import argparse
import hashlib
import json
import re
from pathlib import Path

SELECT = {
    'Mounts': [388, 816, 963, 2523, 2761, 2760, 2759, 1658, 936, 318],
    'Sensors': [984, 2498, 395, 5028, 975, 2634, 974, 632, 2611, 3822, 2991, 2693, 4556, 4558, 4557],
    'Weapons': [598, 2771, 2891, 133, 578, 1144, 2103, 2104]
}
KINDS = {'Mounts': 'launcher', 'Sensors': 'sensor', 'Weapons': 'weapon'}

def read_index(path):
    data = path.read_bytes()
    if data[:2] in (b'\xff\xfe', b'\xfe\xff'):
        text, encoding = data.decode('utf-16'), 'utf-16-bom'
    else:
        try:
            text, encoding = data.decode('utf-8-sig'), 'utf-8-sig'
        except UnicodeDecodeError:
            text, encoding = data.decode('cp1252'), 'cp1252-inferred'
    section = None
    rows = {}
    for line_number, line in enumerate(text.splitlines(), 1):
        if line.endswith(':') and '\t' not in line:
            section = line[:-1]
        match = re.match(r'^(\d+)\t(.+)$', line)
        if match:
            key = (section, int(match[1]))
            if key in rows:
                raise ValueError(f'ID repetido dentro de {section}: {key[1]}')
            rows[key] = {'line': line_number, 'label': match[2]}
    return data, encoding, rows

def build(path):
    raw, encoding, rows = read_index(path)
    digest = hashlib.sha256(raw).hexdigest()
    if digest != '94b411c86a711385c1737a332360dc5d3b5a67eb2060abd9a9eea3fee8f4dd7c':
        raise ValueError('Cambió el índice revisado; confirmar versión/identidad antes de reutilizar esta selección')
    records = []
    for section, identifiers in SELECT.items():
        for number in identifiers:
            row = rows[(section, number)]
            # Only an explicit Rnds/Rounds label supplies a game load count.
            # A year, cell count or missile designation does not become one.
            count = re.search(r'(\d+)(?:x|[- ])\s*(?:Rnds|Rounds)\b', row['label'], re.I)
            records.append({'id': f'cmo-442-{KINDS[section]}-{number}', 'kind': KINDS[section],
                            'name': row['label'], 'database': 'DB3K', 'databaseBuild': 442,
                            'versionBasis': 'supplied-filename', 'section': section,
                            'componentId': number, 'sourceId': 'cmo-db3k-index-442', 'line': row['line'],
                            'confidence': 'low', 'runtimeEnabled': False,
                            'reportedLoadCount': int(count[1]) if count else None,
                            'realLauncherCapacity': None, 'physicalParameters': None,
                            'note': 'Identidad/etiqueta de juego; no certifica compatibilidad, disponibilidad ni prestaciones.'})
    return {'format': 'cielo-cerrado/game-index-review', 'version': 1,
            'source': {'id': 'cmo-db3k-index-442', 'file': path.name, 'sha256': digest,
                       'encoding': encoding, 'role': 'game-index', 'versionBasis': 'supplied-filename'},
            'records': records}

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('index', type=Path)
    parser.add_argument('--output', type=Path)
    args = parser.parse_args()
    rendered = json.dumps(build(args.index), ensure_ascii=False, indent=2, allow_nan=False)
    if args.output:
        args.output.write_text("import { deepFreeze } from '../lib/common.mjs';\n\n"
                               "// Generated by research/read-game-index.py; a selected identity subset.\n"
                               "export const GAME_INDEX_REVIEW = deepFreeze(" + rendered + ");\n")
    else:
        print(rendered)

if __name__ == '__main__':
    main()
